function createfigure(ts1, YMatrix1, ts2, getcolumn1, YMatrix2, getcolumn2)
%CREATEFIGURE(ts1, YMatrix1, ts2, getcolumn1, YMatrix2, getcolumn2)
%  TS1:  vector of stairs x data
%  YMATRIX1:  matrix of stairs y data
%  TS2:  vector of stairs x data
%  GETCOLUMN1:  vector of stairs y data
%  YMATRIX2:  matrix of stairs y data
%  GETCOLUMN2:  vector of stairs y data

%  Auto-generated by MATLAB on 06-Jan-2024 03:58:10

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple stair objects using matrix input to stairs
stairs1 = stairs(ts1,YMatrix1,'Parent',subplot1);
set(stairs1(1),'DisplayName','x ref:1','LineWidth',1,...
    'Color',[0.392156862745098 0.392156862745098 0.392156862745098]);
set(stairs1(2),'DisplayName','ْْX:1','LineWidth',2,...
    'Color',[0 0.447058823529412 0.741176470588235]);

% Create ylabel
ylabel({'X Position (pixels)'});

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 80]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[200 800]);
box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'TickDir','out');
% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create stairs
stairs(ts2,getcolumn1,'DisplayName','X control action:1','Parent',subplot2,...
    'LineWidth',2,...
    'Color',[0 0.447058823529412 0.741176470588235]);

% Create ylabel
ylabel({'Alpha (degree)'});

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 80]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-40 40]);
box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'TickDir','out');
% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create multiple stair objects using matrix input to stairs
stairs2 = stairs(ts1,YMatrix2,'Parent',subplot3);
set(stairs2(1),'DisplayName','y ref:1','LineWidth',1,...
    'Color',[0.392156862745098 0.392156862745098 0.392156862745098]);
set(stairs2(2),'DisplayName','Y:1','LineWidth',2,...
    'Color',[0.850980392156863 0.325490196078431 0.0980392156862745]);

% Create ylabel
ylabel({'Y Position (pixels)'});

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0 80]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[200 800]);
box(subplot3,'on');
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'TickDir','out');
% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create stairs
stairs(ts2,getcolumn2,'DisplayName','y control action:1','Parent',subplot4,...
    'LineWidth',2,...
    'Color',[0.850980392156863 0.325490196078431 0.0980392156862745]);

% Create ylabel
ylabel({'Beta (degree)'});

% Create xlabel
xlabel('Time (seconds)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[0 80]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[-45.6094607251967 44.6765996485112]);
box(subplot4,'on');
hold(subplot4,'off');
% Set the remaining axes properties
set(subplot4,'TickDir','out');
